config/routes.rb
Rails.application.routes.draw do
  concern :trashable do
    collection do
      get :trashed
    end

    member do
      patch  :trash
      patch  :restore
    end
  end

  get 'intro',   to: 'misc#intro',   as: :intro
  get 'support', to: 'misc#support', as: :support

  devise_for :users, controllers: {registrations: "users/registrations"}

  devise_scope :user do
    get 'password',        to: 'users/registrations#password'
    put 'update_password', to: 'users/registrations#update_password'
    get 'confirmation',    to: 'users/registrations#confirmation'
    get 'applications',    to: 'users/registrations#applications'

    authenticated :user do
      root 'misc#intro', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    get 'profile', to: 'users/registrations#edit'
  end

  resources :campaigns, only: [:index, :show]
  resources :templates, only: [:index, :show]
  
  resources :stock_images, only: [:index, :show] do
    post :duplicate
  end

  resources :documents, except: [:show], concerns: [:trashable] do
    collection do
      get :recent
      get :shared
    end

    member do
      get :duplicate
      get :download
      get :job_status, defaults: {format: :json}
      get :preview
      get :share
    end
  end
  
  resources :images, concerns: [:trashable] do
    collection do
      get :choose
      get :recent
      get :shared
    end

    member do
      get  :contextual_crop
      get  :papercrop
      get  :share
    end
  end

  namespace :admin, path: '/admin' do
    root to: "misc#home"

    resources :templates, except: [:show] do
      collection do
        get   :positions
        patch :update_positions
      end
      member do
        patch :remove_image
      end
    end

    get 'documentation',             to: 'misc#documentation', as: :documentation
    get 'documentation/mini_magick', to: 'misc#mini_magick',   as: :mini_magick_documentation

    resources :users, except: [:destroy, :show] do
      collection do
        get :export
      end
      member do
        get :workspace
      end
    end

    resources :campaigns,  except: [:new, :show] do
      member do
        put :whitelist
        put :blacklist
      end
    end

    get 'stats', to: 'misc#stats', as: :stats

    resources :categories, except: [:new, :show]
    resources :affiliates, only:   []
    resources :stock_images
  end
end

app/views/layouts/shared/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-6262329-31"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-6262329-31');
</script>

app/views/layouts/shared/_breadcrumbs.html.erb
<% unless params[:controller].split("/").last == "misc" %>
  <section class="breadcrumbs branding">
    <div class="gradient-mask"></div>
    <%= breadcrumbs(
      class:         :crumbs,
      current_class: :active,
      style:         :inline,
      separator:     ""
    ) %>

    <%= content_for(:breadcrumb_extras) %>
  </section>
<% end %>

app/views/layouts/shared/_devise_head.html.erb
<head>
  <title>AFSCME Toolkit</title>

  <meta charset='utf-8' />
  <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible' />
  <meta content='en-us' http-equiv='Content-Language' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes" /> 

  <!-- Basic Meta -->
  <meta name="title"         content="AFSCME Toolkit" />
  <meta name="copyright"     content="(c) Copyright <%= DateTime.now.year %> AFSCME" /> 

  <!-- CSS -->
  <link rel="stylesheet" href="//toolkit-afscme.bytrilogy.com/theme/css/reset.css" type="text/css" media="screen, projection"/>   
  <link rel="stylesheet" href="//toolkit-afscme.bytrilogy.com/theme/css/type.css" type="text/css" media="screen, projection"/>
  <link rel="stylesheet" href="//toolkit-afscme.bytrilogy.com/theme/css/global.css" type="text/css" media="screen, projection"/>
  <% if params[:controller] == 'users/registrations' and (params[:action] == 'edit' or params[:action] == 'index' or params[:action] == 'applications') %>
  <link rel="stylesheet" href="//toolkit-afscme.bytrilogy.com/theme/css/toolkit.css" type="text/css" media="screen, projection"/>
  <% else %>
  <link rel="stylesheet" href="//toolkit-afscme.bytrilogy.com/theme/css/login.css" type="text/css" media="screen, projection"/>
  <% end %>


  <!-- Scripts -->
  <!-- site.js references ti.utils, which we should not use here -->
  <!-- <script type="text/javascript" src="//toolkit-afscme.bytrilogy.com/theme/scripts/site.js"></script>  -->

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Roboto:700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/shared/_flash.html.erb
<% if flash.count > 0 %>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% elsif alert %>
    <p id="alert"><%= alert %></p>
  <% end %>
<% elsif params[:flash] %>
  <p id="notice"><%= params[:flash] %></p>
<% elsif params[:notice] %>
  <p id="notice"><%= params[:notice] %></p>
<% end %>

app/views/layouts/shared/_footer.html.erb
<footer>

</footer>

<script type="text/javascript">
  $(function () {
    $(".mobile-menu").click(function(){
      $("nav#menu .mobile-dropdown").slideToggle();
      $("nav#menu").toggleClass("expanded");
    });
  });
</script>

app/views/layouts/shared/_head.html.erb
<head>
  <title>AFSCME Toolkit<%= content_for(:title).nil? ? "" : ": #{content_for(:title)}" %></title>

  <meta charset='utf-8' />
  <meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible' />
  <meta content='en-us' http-equiv='Content-Language' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes" /> 

  <!-- Basic Meta -->
  <meta name="title"         content="AFSCME Toolkit" />
  <meta name="copyright"     content="(c) Copyright <%= DateTime.now.year %> AFSCME" /> 

  <!-- CSS -->
  <%= stylesheet_link_tag "reset.css", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "type.css", 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "global.css", 'data-turbolinks-track': 'reload' %>

  <% if params[:controller] == "users" && params[:action] == "sign-in" %>
    <%= stylesheet_link_tag "login", 'data-turbolinks-track': 'reload' %>
  <% else %>
    <%= stylesheet_link_tag "styles", 'data-turbolinks-track': 'reload' %>
  <% end %>

  <!-- Scripts -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700|Roboto:700" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/shared/_header.html.erb
<header>
    <nav>
        <a href="/" title="AFSCME Toolkit" id="logo" itemprop="url">
          <%= image_tag("toolkit-logo.svg", alt: "AFSCME Toolkit", itemprop: "logo") %>
        </a>

        <button title="Menu" class="menu-trigger">
          <span class="hamburger"></span>
          <span class="hide">Menu</span>
        </button>    
        <button title="Your Account" class="user-trigger">
          <span class="icons">u</span>
        </button>    
                
        <ul class="menu left mystuff"> 
          <li>
            <%= link_to "My Stuff", documents_path, title: "My Stuff" %>
            <ol>
              <li><%= link_to "My Designs", documents_path, title: "My Designs" %></li>
              <% if false %>
              <li><%= link_to "Recent", recent_documents_path, title: "Recent" %></li>           
              <li><%= link_to "Shared with me", shared_documents_path, title: "Shared with me" %></li> 
              <% end %>
              <li><%= link_to "My Images", images_path %></li> 
              <% if false %>
              <li><%= link_to "Trash", trash_documents_path, title: "Trash" %></li> 
              <% end %>
            </ol>
          </li>
        </ul>
        
        <ul class="menu left templates"> 
          <li>
            <a href="/campaigns" title="Browse Templates">Browse Templates</a>
            <ol>
              <li><%= link_to "Campaigns", campaigns_path %></li>
              <li><%= link_to "View All", templates_path, title: "View All" %></li>
              <% @categories.each do |category| %>
                <li><%= link_to category.title, templates_path(category_id: category.id), title: category.title %></li>
              <% end %>
            </ol> 
          </li>
        </ul>

        <ul id="user-menu" class="menu right help">
          <li>
            <%= link_to current_user.name, profile_path %>
            <ol>
              <%= render partial: "layouts/shared/user_menus/#{current_user.role.underscore.gsub(' ', '_')}" %>
            </ol>
          </li>
        </ul>

        <% if false %>    
        <!-- THIS IS NOT READY YET -->
        <ul class="menu right help">
          <li>
            <a href="/help" title="Help">Help</a>
            <ol>
                <li><a href="/tutorials" title="Tutorials">Tutorials</a></li>
                <li><a href="/faq" title="FAQ">FAQ</a></li>
                <li><a href="/contact" title="Contact an administrator">Contact an administrator</a></li>            
            </ol>
          </li>
        </ul>
        <% end %>
    </nav>

    <ul class="menu mobile main"> 
      <li><%= link_to "My Stuff", documents_path, title: "My Stuff" %></li>
      <li><a href="/campaigns" title="Browse Templates">Browse Templates</a></li>
    </ul>  
    <ul class="menu mobile user"> 
      <%= link_to "<strong>#{current_user.name}</strong>".html_safe, profile_path %></a>
      <ol>
        <li><%= link_to "My Stuff", documents_path, title: "My Stuff" %></li>
        <% if current_user.admin? %>
        <li><%= link_to "Toolkit Admin", admin_root_path, title: "My Stuff" %></li>
        <% end %>
        <li><%= link_to "Log Out", destroy_user_session_path, method: 'delete' %></li>  
      </ol>
    </ul>  

</header>