config/routes.rb
Rails.application.routes.draw do
  concern :trashable do
    collection do
      get :trashed
    end

    member do
      patch  :trash
      patch  :restore
    end
  end

  get 'intro',   to: 'misc#intro',   as: :intro
  get 'support', to: 'misc#support', as: :support

  devise_for :users, controllers: {registrations: "users/registrations"}

  devise_scope :user do
    get 'password',        to: 'users/registrations#password'
    put 'update_password', to: 'users/registrations#update_password'
    get 'confirmation',    to: 'users/registrations#confirmation'
    get 'applications',    to: 'users/registrations#applications'

    authenticated :user do
      root 'misc#intro', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    get 'profile', to: 'users/registrations#edit'
  end

  resources :campaigns, only: [:index, :show]
  resources :templates, only: [:index, :show]
  
  resources :stock_images, only: [:index, :show] do
    post :duplicate
  end

  resources :documents, except: [:show], concerns: [:trashable] do
    collection do
      get :recent
      get :shared
    end

    member do
      get :duplicate
      get :download
      get :job_status, defaults: {format: :json}
      get :preview
      get :share
    end
  end
  
  resources :images, concerns: [:trashable] do
    collection do
      get :choose
      get :recent
      get :shared
    end

    member do
      get  :contextual_crop
      get  :papercrop
      get  :share
    end
  end

  namespace :admin, path: '/admin' do
    root to: "misc#home"

    resources :templates, except: [:show] do
      collection do
        get   :positions
        patch :update_positions
      end
      member do
        patch :remove_image
      end
    end

    get 'documentation',             to: 'misc#documentation', as: :documentation
    get 'documentation/mini_magick', to: 'misc#mini_magick',   as: :mini_magick_documentation

    resources :users, except: [:destroy, :show] do
      collection do
        get :export
      end
      member do
        get :workspace
      end
    end

    resources :campaigns,  except: [:new, :show] do
      member do
        put :whitelist
        put :blacklist
      end
    end

    get 'stats', to: 'misc#stats', as: :stats

    resources :categories, except: [:new, :show]
    resources :affiliates, only:   []
    resources :stock_images
  end
end

app/models/document.rb
class Document < ApplicationRecord
  include Status

  has_and_belongs_to_many :users
  
  has_many :data
  has_many :document_users, class_name: "DocumentUser"

  belongs_to :creator, class_name: "User", foreign_key: :creator_id
  belongs_to :template

  validates_presence_of :template, :title, :description, :status

  scope :recent,         ->(user) { where("documents.creator_id = ? AND documents.created_at >= ?", user.id, DateTime.now - 2.weeks) }
  scope :shared_with_me, ->(user) { all.joins(:documents_users).where("user_id = ? and documents_users.user_id != ?", user.id, user.id) }
  
  scope :rendered, -> { where(generated: true) }
  scope :newest,   -> { order(created_at: :desc) }

  attr_accessor :debug_pdf

  ### GENERATOR METHODS
  def generate_pdf
    reload # Grab the latest copy from the database

    av = ActionView::Base.new
    av.view_paths = ActionController::Base.view_paths
    pdf_html = av.render(template: "documents/build.pdf.erb", locals: {document: self})
    pdf = WickedPdf.new.pdf_from_string(pdf_html, pdf_options)

    File.open(pdf_path, 'wb') {|file| file << pdf}
    upload_to_s3!(filepath: pdf_path)
  end

  def generate_share_graphic
    reload # Grab the latest copy from the database
    config = Rails.application.config.wkhtmltoimage

    %x(#{config["cmd"]} --quality 100 --format jpg #{config["host"]}/documents/#{id}/preview #{share_graphic_path})

    upload_to_s3!(filepath: share_graphic_path)
  end

  def generate_thumbnail
    # Assign the correct paths depending on the type of template
    case template.format
    when "pdf"
      document_path = pdf_path
      thumb_path    = pdf_thumbnail_path
    when "png"
      document_path = share_graphic_path
      thumb_path    = share_graphic_thumbnail_path
    end

    # Create a thumbnail from the document
    thumb = ::MiniMagick::Image.open(document_path) 
    thumb.format "png"
    thumb.resize "348x269"
    
    # Save the thumbnail and upload it to S3
    FileUtils.cp(thumb.path, thumb_path)
    upload_to_s3!(filepath: thumb_path)
  end

  ### PATHING METHODS
  # => /rails_root/public/pdfs/1.pdf
  def pdf_path
    Rails.root.join("public", "pdfs", "#{id}.pdf").to_s
  end

  # => /rails_root/public/pdfs/1_thumb.png
  def pdf_thumbnail_path
    Rails.root.join("public", "pdfs", "#{id}_thumb.png").to_s
  end

  # => /rails_root/public/share_graphics/1.jpg
  def share_graphic_path
    Rails.root.join("public", "share_graphics", "#{id}.jpg").to_s
  end

  # => /rails_root/public/share_graphics/1_thumb.png
  def share_graphic_thumbnail_path
    Rails.root.join("public", "share_graphics", "#{id}_thumb.png").to_s
  end

  ### URL METHODS
  # => https://s3.amazonaws.com/toolkit.afscme.org/folder/1.pdf
  def pdf_s3_url
    "https://s3.amazonaws.com/toolkit.afscme.org/#{s3_path(filename: "#{id}.pdf")}"
  end

  # => https://s3.amazonaws.com/toolkit.afscme.org/folder/1_thumb.png
  def thumbnail_s3_url
    "https://s3.amazonaws.com/toolkit.afscme.org/#{s3_path(filename: "#{id}_thumb.png")}"
  end

  # => https://s3.amazonaws.com/toolkit.afscme.org/folder/1.jpg
  def share_graphic_s3_url
    "https://s3.amazonaws.com/toolkit.afscme.org/#{s3_path(filename: "#{id}.jpg")}"
  end
  
  # => https://toolkit.afscme.org/pdfs/1_thumb.png
  def pdf_thumbnail_url
    "#{Rails.application.config.wkhtmltoimage["host"]}/pdfs/#{id}_thumb.png"
  end

  # => https://toolkit.afscme.org/pdfs/1.pdf?1234567890
  def pdf_url_with_timestamp
    "#{pdf_url}?#{DateTime.now.to_i}"
  end

  # => https://toolkit.afscme.org/share_graphics/1.jpg?1234567890
  def share_graphic_url_with_timestamp
    "#{share_graphic_url}?#{DateTime.now.to_i}"
  end

  # OTHER METHODS
  def method_missing(meth, *args, &block)
    data.find{|d| d.key == meth.to_s}&.value || ""
  end

  # Updates the document with S3 URLs for all the documents, and deletes all files from the local filesystem.
  def cleanup!
    case template.format
    when "pdf"
      update!(pdf_url: pdf_s3_url, thumbnail_url: thumbnail_s3_url, share_graphic_url: nil)
    when "png"
      update!(share_graphic_url: share_graphic_s3_url, thumbnail_url: thumbnail_s3_url, pdf_url: nil)
    end

    begin
      [pdf_path, pdf_thumbnail_path, share_graphic_path, share_graphic_thumbnail_path].each do |path|
        FileUtils.rm(path)
      end
    rescue => e
      # File doesn't exist. We don't care.
    end

    self.update!(generated: true)
  end

  def duplicate!(user)
    begin
      # Duplicate and save the document
      new_self = self.dup
      new_self.save!
      
      # Create the join record and remove the PDF.
      DocumentUser.create!(document_id: new_self.id, user_id: user.id)
      new_self.assign_attributes(pdf: nil)
      new_self.save!

      # Duplicate the document's data
      self.data.each do |datum|
        new_datum = datum.dup
        new_datum.document_id = new_self.id
        new_datum.save!
      end

      new_self
    rescue => e
      false
    end
  end

  def pdf_options
    if crop_marks
      height = template.height + 0.75
      width  = template.width  + 0.75
    else
      height = template.height
      width  = template.width
    end

    {
      pdf:           title,
      template:      "documents/build.pdf.erb",
      disposition:   :inline,
      orientation:   template.orientation,
      grayscale:     false,
      lowquality:    false,
      image_quality: 94,
      show_as_html:  debug_pdf,
      page_height:   "#{height}#{template.unit}",
      page_width:    "#{width}#{template.unit}",
      zoom:          1,
      margin:        { top: 0, bottom: 0, left: 0, right: 0 }
    }
  end

  # PAPERCLIP LEGACY METHODS
  def pdf
    OpenStruct.new(url: pdf_url)
  end

  def thumbnail
    OpenStruct.new(url: pdf_thumbnail_url)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include Trashable

  protect_from_forgery except: :create

  before_action :assign_sidebar_vars, only: [:index, :recent, :shared, :trashed]

  skip_before_action :authenticate_user!, only: [:preview]

  # POST /documents
  def create
    @document = Document.new(document_params)

    if @document.save
      DocumentUser.create!(document_id: @document.id, user_id: current_user.id)
      create_data
      DocumentGeneratorJob.perform_async(@document)

      redirect_to documents_path(generating: @document.id), notice: "Document created!"
    else
      redirect_back fallback_location: documents_path
    end
  end

  # GET /documents/1/duplicate
  def duplicate
    @original_document = Document.find(params[:id])
    authorize @original_document

    if @document = @original_document.duplicate!(current_user)
      redirect_to edit_document_path(@document), notice: "#{@original_document.title} was duplicated and saved. You are editing the new document."
    else
      redirect_to edit_document_path(@original_document), notice: "Cannot duplicate this document. Please try again."
    end
  end

  # GET /documents/1/edit
  def edit
    load_document
    assign_records
  end

  # GET /documents/1/download
  def download
    load_document
    DocumentGeneratorJob.perform_async(@document)
    head :no_content
  end

  # GET /documents
  def index
    if params[:category_id]
      @filtered_documents = @documents.select{ |document| 
        document.template.category_id == params[:category_id].to_i
      }.reverse
    else
      @filtered_documents = @documents.reverse
    end

    @filtered_documents = paginate(@filtered_documents)
  end

  # GET /documents/1/job_status
  def job_status
    load_document

    respond_to do |format|
      format.json do
        if @document.generated?
          case @document.template.format
          when "pdf"
            render json: {status: :complete, thumbnail: @document.thumbnail_s3_url, pdf: @document.pdf_s3_url}
          when "png"
            render json: {status: :complete, thumbnail: @document.thumbnail_s3_url, pdf: @document.share_graphic_s3_url}
          end
        else
          render json: {status: :incomplete}
        end
      end
    end
  end

  # GET /documents/new
  def new
    @template = Template.find(params[:template_id])
    @document = Document.new(template_id: @template.id, title: @template.title, description: @template.description)
    authorize_campaign!(@document)
    assign_records
  end

  # GET /documents/1/preview
  def preview
    load_document
    @document.debug_pdf = true
    # render @document.pdf_options

    av = ActionView::Base.new
    av.view_paths = ActionController::Base.view_paths
    html = av.render(template: "documents/build.pdf.erb", locals: {document: @document})
    render html: html
  end

  # GET /documents/recent
  def recent
    @filtered_documents = Document.includes(:template).recent(current_user).not_trashed.reverse
    @filtered_documents = paginate(@filtered_documents)
    render :index
  end

  # GET /documents/1/share
  def share
    @document = Document.includes(:template).find(params[:id])
  end

  # GET /documents/shared
  def shared
    @filtered_documents = Document.includes(:template).shared_with_me(current_user)
    @filtered_documents = paginate(@filtered_documents)
    @shared = true
    render :index
  end

  # PATCH /documents/1
  def update
    load_document
    @document.pdf = nil
    @document.thumbnail = nil

    if @document.update_attributes(document_params)
      ActiveRecord::Base.transaction do
        delete_data
        create_data
      end

      DocumentGeneratorJob.perform_async(@document)

      redirect_to edit_document_path(@document, generating: true), notice: "Your changes have been saved."
    else
      redirect_back fallback_location: documents_path, error: alert_message
    end
  end

  protected

  def assign_sidebar_vars
    if current_user
      @documents = current_user.documents.includes(:template, :creator).not_trashed
      @images = current_user.images.not_trashed
    else
      @documents = Document.includes(:template, :creator).not_trashed
      @images = Image.not_trashed
    end

    @recent = @documents.recent(current_user)

    @campaigns = current_user.campaigns.publish
    @trashed   = current_user.documents.trash
    @stock_images = StockImage.all


    @sidebar_vars = @categories.inject([]) do |sidebar_vars, category|
      sidebar_vars << {
        category_id: category.id,
        title:       category.title,
        items:       @documents.select{|document| document.template.category_id == category.id}
      }
    end
  end

  private

  def assign_records
    @template  = @document.template
    @campaigns = @template.campaigns
    @custom_branding = current_user.custom_branding?
  end

  def create_data
    select_data = params.delete(:select_data)

    params.delete(:data).each do |key, value|
      Datum.create!(document_id: @document.id, key: key, value: value, field_id: select_data[key])
    end
  end

  def delete_data
    @document.data.destroy_all
  end

  def document_params
    params.require(:document).permit(:title, :description, :status, :crop_marks, :template_id, :creator_id)
  end

  def load_document
    @document = Document.find(params[:id])

    unless params[:action] == "preview"
      authorize_campaign!(@document)
      authorize @document
    end
  end
end

app/views/documents/_breadcrumb_extras.html.erb
<% content_for :breadcrumb_extras do %>
  <ol class="options cf">
    <li><a href="#" title="Save" data-save="true"><span class="icons">V</span> Save</a></li>
    <% unless @document.new_record? %>
      <li><%= link_to "<span class='icons'>c</span> Duplicate".html_safe, duplicate_document_path(@document), title: "Duplicate" %></li>
      <li style="display:none;"><%= link_to "<span class='icons'>s</span> Share".html_safe, share_document_path(@document), title: "Share" %></li>
      <li>
        <%= link_to(
          "<span class='icons'>d</span> Download".html_safe,
          @document.pdf&.url,
          target: :blank,
          title:  changed_document_message,
          class:  "download-document",
          style:  @document.pdf_file_name ? "" : "display:none"
        ) %>
      </li>
			<li>
			  <%= link_to(
			    "<span class='icons'>x</span> Delete".html_safe,
			    trash_document_path(@document),
			    title:  "Delete",
			    method: :patch,
			    data:   {confirm: "Are you sure that you want to move this document to the trash?"} 
			  ) %>
			</li>
    <% end %>
  </ol>
<% end %>

app/views/documents/_document.html.erb
<%
  if document.thumbnail_url.nil?
    thumbnail = document.template.thumbnail&.url
  else
    thumbnail = document.thumbnail_url
  end
%>

<div class="document">
  <%= link_to(
    "", 
    edit_document_path(document),
    class: "document-thumbnail",
    title: document.title,
    style: "background-image: url('#{thumbnail}');",
    data: {
      behavior: "download"
    }
  ) %>

  <%= link_to(
      document.title,
      edit_document_path(document),
      class: "document-title",
      title: document.title 
  ) %>

  <ul class="options"> 
    <li>
      <a href="javascript:void(0);" title="Options" class="icons">+</a>
      <ol>
        <% case document.status %>
        <% when "trash" %>
          <%= render partial: "documents/menus/trash", locals: {document: document} %>
        <% else %>
          <%= render partial: "documents/menus/publish", locals: {document: document} %>
        <% end %>
      </ol>
    </li>
  </ul>
</div>

app/views/documents/_form.html.erb
<%= form_for(@document,
  html: {
    novalidate: "novalidate", 
    data: {
      "document"     => true,
      "crop-enabled" => @template.croppable?,
      "template-id"  => @template.id
    }
  }
) do |f| %>
  <%= f.hidden_field :template_id, value: @template.id %>
  <%= f.hidden_field :status, value: :publish %>
  
  <% if @document.new_record? %>
    <%= f.hidden_field :creator_id, value: current_user.id %>
  <% end %>

  <main class="clearfix">
    <aside class="preview">
      <ol>
        <li>
          <% unless @document.new_record? %>
            <label>
              <%= link_to(
                "Launch full size preview",
                preview_document_path(@document),
                class: "full-preview active",
                target: :_blank,
                title:  changed_document_message
              ) %>
              Preview
            </label>
          <% end %>

          <% if @template.numbered_image_url %>
            <%= image_tag @template.numbered_image_url %>
          <% end %>
        </li>
        <li>
          <%= f.label :title %>
          <%= f.text_field :title %>
        </li>

        <li>
          <%= f.label :description %>
          <%= f.text_area :description %> 
        </li>
                
        <li><strong class="metadata-label">Dimensions</strong><%= dimensions(@template) %></li>
        <li><strong class="metadata-label">Toolkit</strong><%= @campaign.title if @campaign %></li>
        <li><strong class="metadata-label">Type</strong>Flyer</li>

      <% unless @template.crop_marks == 'no_crop_marks' %>
        <li class="crop-radio">
          <%= f.check_box :crop_marks, checked: check_crop_marks? %> 
          <%= f.label :crop_marks do %>
            <div class="radio-button"></div>
            Display Crop Marks
          <% end %>
        </li>
      <% end %>
      </ol>
    </aside>
        
    <section class="workspace cf">

      <% unless @custom_branding  %>
      <script>
      $(document).ready(function(){
        var _branding_div = $('#branding');
        if (_branding_div) { $(_branding_div).remove(); }
      });
      </script>
      <% end %>

      <%= @template.form_markup.html_safe %>

      <div class="buttons small cf">
        <% unless @document.new_record? %>
          <%= link_to(
            "Download".html_safe,
            @document.pdf&.url,
            target: :blank,
            class:  "preview action button download-document",
            title:  changed_document_message,
            style:  @document.persisted? ? "display:inline" : "display:none"
          ) %>
        <% end %>
        <%= f.button "Save", class: "button save active" %>
      </div>
    </section>
  </main>
<% end %>

<script type="text/javascript">
  tinyMCE.init({
    branding: false,
    menubar:  "edit view format tools",
    plugins:  "code searchreplace lists",
    selector: "textarea.tinymce",
    toolbar:  "styleselect | bold italic underline strikethrough | bullist numlist | indent outdent | alignleft aligncenter alignright alignjustify | undo redo",
    extended_valid_elements: "script[src] style",
    init_instance_callback: function(editor) {
      window.Toolkit.Document.fillWysiwyg(editor);

      editor.on('Change', function (e) {
        $field  = $("#"+e.target.id);
        content = e.level.content;
        $field.val(content).trigger("change");
      });
    }
  });
</script>

app/views/documents/_init_tiny_mce.html.erb
<script>
  function initTinyMCE() {
    if (typeof tinyMCE != 'undefined') {
      tinyMCE.init({
        selector: "textarea.tinymce",
        toolbar: ["styleselect | bold italic | undo redo"],
        branding: false,
        menubar: "edit insert view format table tools",
        plugins: "code,searchreplace",
        extended_valid_elements: "script[src],style"
      });
    } else {
      setTimeout(initTinyMCE, 50);
    }
  }

$(document).ready(function(){
	initTinyMCE();
});

</script>

app/views/documents/_populate_data.html.erb
<script type="text/javascript">
  window.Toolkit.Document.savedData = {};

  <% @document.data.each do |datum| %>
    window.Toolkit.Document.savedData.<%= datum.key %> = {
      fieldID: <%= datum.field_id.to_json.html_safe %>,
      value:   <%= datum.value.to_json.html_safe %>
    };
  <% end %>
</script>

<!-- This is a hidden div that holds any custom text for the form so we can parse it with jQuery and insert it into the correct field. -->
<div id="custom-text" style="display:none"></div>

app/views/documents/_sidebar_nav.html.erb
<ul> 
  <li <% if params[:controller] == 'documents' && params[:action] == 'index' %>class="active"<% end %>>
    <%= link_to "My Designs", documents_path, title: "My Designs" %>
    <div class="contents-counter"><%= @documents.count %></div>
  </li>
        
  <li <% if params[:action] == 'recent' %>class="active"<% end %>>
    <%= link_to "Recent", recent_documents_path, title: "Recent" %>
    <div class="contents-counter"><%= @recent.count %></div>
  </li>

  <!-- shared with me here when done -->

  <li>
    <%= link_to "Images", images_path, title: "Images" %>
    <div class="contents-counter"><%= @images.count %></div>
  </li>  

  <li>
    <%= link_to "Stock Images", stock_images_path, title: "Stock Images" %>
    <div class="contents-counter"><%= @stock_images.count %></div>
  </li>  

  <li <% if params[:action] == 'trashed' %>class="active"<% end %>>
    <%= link_to "Trash", trashed_documents_path, title: "Trash" %>
    <div class="contents-counter"><%= @trashed.count %></div>
  </li>
</ul>

app/views/documents/build.pdf.erb
<% @document ||= document %>
<%= ERB.new(@document.template.pdf_markup).result(binding).html_safe %>

app/views/documents/edit.html.erb
<% content_for :title, "Edit Document: #{@document.title}" %>
<%= render partial: "/shared/errors", locals: {record: @document} %>

<% breadcrumb :edit_document, @document, @template %>
<%= render partial: "documents/breadcrumb_extras" %>
<%= render partial: "documents/populate_data" %>

<%= render 'form' %>
<%= render partial: "images/modal" %>

<% if params[:generating] %>
  <script type="text/javascript">
    $(document).ready(function(){
      new window.Toolkit.Job(undefined, "pdfAndThumbnail", <%= @document.id %>)
    });
  </script>
<% end %>

app/views/documents/index.html.erb
<% content_for :title, "My Designs" %>
<% if params[:action] == 'recent' %>
	<% breadcrumb :recent_documents %>
<% else %>
	<% breadcrumb :my_designs %>
<% end %>

<aside>
  <%= render partial: "documents/sidebar_nav" %>
</aside>

<% if @filtered_documents.count > 0 %>
  <section class="workspace cf">
    <%= render   @filtered_documents %>
    <%= paginate @filtered_documents %>
  </section>
<% else %>
	<% if @shared %>
		<p class="no-results">You have not had any documents shared with you.</p>
	<% else %>
		<p class="no-results">You have not created any documents of this type.</p>
	<% end %>
<% end %>

<% if params[:generating] %>
  <script type="text/javascript">
    $(document).ready(function(){
      $el = $("a[data-id='<%= params[:generating] %>']").closest(".document");
      new window.Toolkit.Job($el, "pdfAndThumbnail", <%= params[:generating] %>);
    });
  </script>
<% end %>

app/views/documents/new.html.erb
<% content_for :title, "New Document" %>
<%= render partial: "/shared/errors", locals: {record: @document} %>

<% breadcrumb :new_document, @template %>
<%= render partial: "documents/breadcrumb_extras" %>

<%= render 'form' %>
<%= render partial: "images/modal" %>

app/views/documents/share.html.erb
<% content_for :title, "Share Document: #{@document.title}" %>
<% breadcrumb :share_document, @document, @template %>

Sharing <%= @document.title %>

app/views/documents/trashed.html.erb
<% content_for :title, "Trashed Documents" %>
<% breadcrumb :trashed_documents %>

<aside>
  <%= render partial: "documents/sidebar_nav" %>  
</aside>

<section class="workspace cf">
  <section class="image-grid cf">
    <% if @trashed.count > 0 %>
      <%= render @trashed %>
    <% else %>
      <p class="no-results">There are no documents in the trash.</p>
    <% end %>
  </section>
</section>