config/routes.rb
Rails.application.routes.draw do
  concern :trashable do
    collection do
      get :trashed
    end

    member do
      patch  :trash
      patch  :restore
    end
  end

  get 'intro',   to: 'misc#intro',   as: :intro
  get 'support', to: 'misc#support', as: :support

  devise_for :users, controllers: {registrations: "users/registrations"}

  devise_scope :user do
    get 'password',        to: 'users/registrations#password'
    put 'update_password', to: 'users/registrations#update_password'
    get 'confirmation',    to: 'users/registrations#confirmation'
    get 'applications',    to: 'users/registrations#applications'

    authenticated :user do
      root 'misc#intro', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    get 'profile', to: 'users/registrations#edit'
  end

  resources :campaigns, only: [:index, :show]
  resources :templates, only: [:index, :show]
  
  resources :stock_images, only: [:index, :show] do
    post :duplicate
  end

  resources :documents, except: [:show], concerns: [:trashable] do
    collection do
      get :recent
      get :shared
    end

    member do
      get :duplicate
      get :download
      get :job_status, defaults: {format: :json}
      get :preview
      get :share
    end
  end
  
  resources :images, concerns: [:trashable] do
    collection do
      get :choose
      get :recent
      get :shared
    end

    member do
      get  :contextual_crop
      get  :papercrop
      get  :share
    end
  end

  namespace :admin, path: '/admin' do
    root to: "misc#home"

    resources :templates, except: [:show] do
      collection do
        get   :positions
        patch :update_positions
      end
      member do
        patch :remove_image
      end
    end

    get 'documentation',             to: 'misc#documentation', as: :documentation
    get 'documentation/mini_magick', to: 'misc#mini_magick',   as: :mini_magick_documentation

    resources :users, except: [:destroy, :show] do
      collection do
        get :export
      end
      member do
        get :workspace
      end
    end

    resources :campaigns,  except: [:new, :show] do
      member do
        put :whitelist
        put :blacklist
      end
    end

    get 'stats', to: 'misc#stats', as: :stats

    resources :categories, except: [:new, :show]
    resources :affiliates, only:   []
    resources :stock_images
  end
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  include Status
  include Tree

  has_and_belongs_to_many :templates, join_table: :campaigns_templates
  has_and_belongs_to_many :users,     join_table: :campaigns_users

  validates_presence_of :title

  def audit!(message)
    update_attributes(audit: "#{message} on #{DateTime.now.strftime("%D %r")}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :documents
  has_and_belongs_to_many :images
  has_and_belongs_to_many :campaigns, join_table: :campaigns_users

  validates_length_of :first_name, :maximum => 30, :message => "must be less than 30 characters"
  validates_length_of :last_name, :maximum => 30, :message => "must be less than 30 characters"

  belongs_to :affiliate

  scope :approved, -> { where(approved: 1) }
  scope :unapproved, -> { where(approved: 0, rejected: 0) }
  scope :unapproved_and_needs_reminder, -> { where(approved: 0, rejected: 0).where('approval_reminder_sent IS NULL and created_at < ?', DateTime.now - 2.days) }
  scope :needs_admin_notification, -> { where(approved: 0, rejected: 0).where('created_at > ?', DateTime.now - 24.hours) }

  scope :rejected, -> { where(rejected: 1) }
  scope :approvers, -> { where(role: 'Vetter') }

  after_create :access_all_campaigns!
  after_create :send_admin_emails

  attr_accessor :quiet # Set to true to disable emails to the user

  ROLES = ['User', 'Local President', 'Vetter', 'Administrator']
  
  DEPARTMENTS = [ 
    'IU-Communications', 
    'IU-Organizing', 
    'IU-Political', 
    'Council-Communications',
    'Council-Organizing', 
    'Council-Political', 
    'Local-President', 
    'Research', 
    'Data & Analytics',
    'Education', 
    'Executive Office',
    'Federal Government Affairs',
    'Information Technology',
    'Retirees'
  ]

  class << self
    def to_csv
      CSV.generate do |csv|
        csv << [
          "ID", "First Name", "Last Name", "Email", "Zip Code", "Cell Phone",
          "Department", "Council", "Local #", "Affiliate", "Vetter Region",
          "Role", "Approved?", "Rejected?", "Receive Alerts?", "Custom Branding?",
          "Sign In Count", "Most Recent Sign In", "Created At", "Approval Reminder Sent At"
        ]

        User.includes(:affiliate).all.order(created_at: :desc).each do |user|
          csv << [
            user.id, user.first_name, user.last_name, user.email, user.zip_code, user.cell_phone,
            user.department, user.council, user.local_number, user.affiliate.title, user.vetter_region,
            user.role, user.approved?, user.rejected?, user.receive_alerts?, user.custom_branding?,
            user.sign_in_count, user.current_sign_in_at, user.created_at, user.approval_reminder_sent
          ]
        end
      end
    end
  end

  def send_account_notification(status)
    unless quiet
      case status
      when 'approved'
          AdminMailer.send_account_activation(self).deliver_now
          self.send_reset_password_instructions
      when 'rejected'
          AdminMailer.send_account_rejection(self).deliver_now
      when 'unapproved'
          AdminMailer.send_account_suspension(self).deliver_now
      end
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def password_required?
    #having trouble with this when admins are un-approving a current user that was previously approved
    false
    ##self.approved? ? true : false
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def admin?
    self.role == 'Administrator'
  end

  def vetter?
    self.role == 'Vetter'
  end

  def set_accessible_campaigns!(campaigns)
    CampaignUser.where(user_id: id).destroy_all

    Array(campaigns).each do |campaign|
      CampaignUser.create!(campaign_id: campaign, user_id: id)
    end
  end

  ## auth methods for devise
  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end

  def regional_approvers
    region = self.affiliate.region
    User.approvers.select {|user| user.vetter_region == region}
  end
  ## end of auth methods for devise
  
  protected

  def send_admin_emails
    AdminMailer.new_user_waiting_for_approval(self).deliver_now
    approver = self.regional_approvers.length > 0 ? self.regional_approvers.first : User.find(MAIL_CONFIG['default_approver'])
    unless self.admin?
      AdminMailer.notification_to_approvers(self, approver).deliver_now
    end
  end

  def access_all_campaigns!
    Campaign.publish.each do |campaign|
      CampaignUser.create!(campaign: campaign, user: self)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  # POST /admin/users

  def create
    @user = User.new(user_params)
    authorize @user
    ## we could do the following to set an initial, hidden password -- which avoids some password confirmation issues later
    ## new_password = Devise.friendly_token(length = 50)
    ## @user.password = new_password
    ## @user.password_confirmation = new_password

    if @user.save
      if @user.approved
        @user.send_reset_password_instructions
      end

      redirect_to edit_admin_user_path(@user), notice: "User created and activation email sent!"
    else
      @affiliates = Affiliate.order(:state,:title)
      render :new
    end
  end

  # GET /admin/users/1/edit
  def edit
    load_user
    @body_class        = 'toolkit USER'
    @header_navigation = true

    @affiliates    = Affiliate.order(:state,:title)
    @all_campaigns = Campaign.publish
    @template_ids  = @user.documents.map(&:template_id)
    @templates     = Template.find(@template_ids.uniq)
  end

  # GET /admin/users/export.csv
  def export
    respond_to do |format|
      format.csv { send_data User.to_csv, filename: "users-#{DateTime.now.to_i}.csv" }
    end
  end

  # GET /admin/users
  def index
    @approved = User.includes(:affiliate).approved
    @unapproved = User.includes(:affiliate).unapproved
    @rejected = User.includes(:affiliate).rejected
    authorize @approved
  end

  # GET /admin/users/new
  def new
    @user = User.new
    authorize @user
    @affiliates = Affiliate.order(:state,:title)
  end

  # PATCH /admin/users/1
  def update
    load_user

    if params[:quiet_rejection] == '1'
      @user.quiet = true
      params[:user][:rejected] = '1'
    end  

    account_status = set_account_status

    if @user.update_attributes(user_params)
      if params[:campaigns]
        @user.set_accessible_campaigns!(params[:campaigns])
      end
      
      if account_status != 'same'
        @user.send_account_notification(account_status)
      end
      if @user.role == 'Administrator'  
        redirect_to edit_admin_user_path(@user), notice: "User updated!"
      else 
        redirect_to profile_path, notice: "User updated!"
      end
    else
      @body_class = 'toolkit USER'
      @header_navigation = true
      @affiliates = Affiliate.order(:state,:title)

      redirect_to edit_admin_user_path(@user), notice: "There was a problem updating the user."
    end
  end

  # GET /admin/users/1/workspace
  def workspace
    @user = User.find(params[:id])
    @documents = paginate(@user.documents)
  end

  private

  def load_user
    @user = User.includes(:affiliate).find(params[:id])
    authorize @user
  end

  def set_account_status
    if !@user.approved? && params[:user][:approved] == '1'
      'approved'
    elsif params[:user][:approved] == '0' && @user.approved?
      'unapproved'
    elsif !@user.rejected? && params[:user][:rejected] == '1'
      'rejected'
    else
      'same'
    end
  end

  def user_params
    params.require(:user).permit(
      :first_name, :last_name, :email, :approved, :rejected, :zip_code, :affiliate_id, :department,
      :local_number, :title, :cell_phone, :receive_alerts, :role, :custom_branding, :vetter_region
    )
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.

  def confirmation
  end

  def edit
    load_user
  	@body_class = 'toolkit profile'
  	@header_navigation = true
    @affiliates = Affiliate.order(:state,:title)
  end

  def password
    load_user
  end

  def update_password
    load_user
    # puts "\n\n\n#{params['user'].inspect}\n\n\n"
    if params['user']['password'] == params['user']['password_confirmation']
      @user.password = params['user']['password']
      @user.password_confirmation = params['user']['password_confirmation']
      if @user.update(password_params)
        bypass_sign_in(@user)
        redirect_to profile_path, notice: "Password changed!"
      else
        redirect_to profile_path, notice: "There was a problem changing your password"
      end
    else
      redirect_to profile_path, notice: "Password and confirmation must match."
    end
  end

  protected

  def after_sign_up_path_for(resource)
    confirmation_path
  end

  def after_inactive_sign_up_path_for(resource)
    confirmation_path
  end

  private

  def check_captcha
    unless verify_recaptcha
      self.resource = resource_class.new sign_up_params
      resource.validate # Look for any other validation errors besides reCAPTCHA
      flash[:recaptcha_error] = "reCAPTCHA test failed. You must confirm you are not a robot."
      redirect_back fallback_location: new_user_registration_path
    end 
  end

  def load_user
    @user = current_user
    authorize @user, pundit_policy
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  # UserPolicy has policies for both this controller and Admin::UsersController.
  # Some of the actions overlap, so to differentiate the two, devise_ is prepended
  # for policies in this controller.
  def pundit_policy
    "devise_#{params[:action]}?"
  end

end

app/views/admin/users/_form.html.erb
<script>
$(document).ready(function(){

  if ($('#user_role').val() != 'Vetter'){
    $('#user_vetter_region').prop('disabled',true);
  }

  $('#user_email').click(function(){ $(this).removeAttr('readonly'); }) // this is to disable Chrome autofill, but allow for field to be edited

  $('#user_role').change(function(){
    if ( $(this).val() != 'Vetter' ) {
      $('#user_vetter_region').val('').prop('disabled',true);
    }
    else {
      $('#user_vetter_region').val('').prop('disabled',false);
    }
  })
});
</script>

<div class="cf">     
  <ol>
    <li>
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, autofocus: true %>              
    </li>
      
    <li>
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, autofocus: true %>              
    </li>
      
    <li>
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: :off, readonly: true %>
    </li>
      
    <li>
      <%= f.label :zip_code %><br />
      <%= f.text_field :zip_code, autofocus: true %>              
    </li>
      
    <li>
      <%= f.label :affiliate_id, 'Affiliate/Council' %><br />
      <%= f.select(:affiliate_id) do %>
        <%= options_for_select(@affiliates.collect { |aff| [aff.to_s, aff.id] }, @user.affiliate_id) %>
      <% end %>          
    </li>
      
    <li>
      <%= f.label :local_number %><br />
      <%= f.text_field :local_number, autofocus: true %>              
    </li>
      
    <li>
      <%= f.label :department %>
      <%= f.select(:department) do %>
        <%= options_for_select( User::DEPARTMENTS, @user.department) %>
      <% end %>
    </li>

    <li>
      <%= f.label :cell_phone %><br />
      <%= f.text_field :cell_phone, autofocus: true %>              
    </li>

    <li class="checkbox clearfix">
      <%= f.check_box :custom_branding %>  
      <%= f.label :custom_branding, 'User will see custom branding options in templates (e.g., CSEA)' %></label>
    </li>
      
    <li class="checkbox clearfix">
      <%= f.check_box :receive_alerts %>  
      <%= f.label :receive_alerts, 'By providing my cell phone number, I agree to receive text, autodialed and/or prerecorded messages at the cell number provided above on any subject from AFSCME and affiliated labor, political, or charitable organizations. Message and data rates may apply.' %></label>
    </li>
  </ol> 

  <ol>
    <li>
      <%= f.label :role %><br />
      <%= f.select(:role) do %>
        <%= options_for_select( User::ROLES, @user.role) %>
      <% end %>
    </li>

    <li>
      <%= f.label :vetter_region%></br>
      <%= f.select(:vetter_region) do %>
        <%= options_for_select( ['','Central','Eastern','Southern','Western'], @user.vetter_region) %>
      <% end %>
    </li>

    <% unless @user.rejected? %>
      <li class="checkbox clearfix">
        <%= f.check_box :approved %>  
        <%= f.label :approved, !@user.approved? ? "Activate User (sends email notice with login information)" : "User is active; uncheck/save to deactivate and notify user." %></label>
      </li>
     <% end %>

    <% unless @user.approved? || @user.new_record? %>
      <li class="checkbox clearfix">
        <%= f.check_box :rejected %>  
        <%= f.label :rejected, !@user.rejected? ? "Decline Access WITH email notification" : "User has been rejected; uncheck/save to enter back into appproval queue (must approve access subsequently)" %></label>
      </li>

      <!-- This next block is for silent rejection. But don't show it if the user was already rejected because it will show the same checkbox as above. -->
      <% unless @user.rejected? %>
        <li class="checkbox clearfix">
          <%= check_box_tag :quiet_rejection %>  
          <%= label_tag :quiet_rejection, !@user.rejected? ? "Decline Access WITHOUT email notification" : "User has been rejected; uncheck/save to enter back into appproval queue (must approve access subsequently)" %></label>
        </li>
      <% end %>
    <% end %>

    <% if @user.persisted? %>
      <li>
        <%= label_tag "Campaigns" %>
        <ul>
          <% Array(@all_campaigns).each do |campaign| %>
            <li class="checkbox clearfix">
              <%= check_box_tag "campaigns[]", campaign.id, @user.campaigns.include?(campaign), id: "campaign-checkbox-#{campaign.id}" %>
              <%= label_tag "campaign-checkbox-#{campaign.id}", campaign.title %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ol>
</div>

app/views/admin/users/_header_row.html.erb
<div class="row header">
  <div class="col one name">Name</div>
  <div class="col one affiliate-council">Affiliate/Council</div>
  <div class="col one local">Local</div>
  <div class="col one title">Department</div>
  <div class="col one date-submitted">Date Submitted</div>
</div><!--row header-->

app/views/admin/users/_user_row.html.erb
<div class="notifications">
  <div class="row applicant">
    <div class="col one name"><a href="/admin/users/<%= user.id %>/edit" title="<%= user.name %>"><span class="icons">e</span> <%= user.name %></a></div>
    <div class="col one affiliate-council"><%= user.affiliate.title %></div>
    <div class="col one local"><%= user.local_number %></div>
    <div class="col one title"><%= user.department %></div>
    <div class="col one date-submitted"><%= user.created_at.strftime("%m/%d/%Y") %></div>
  </div>
</div><!--notifications-->

app/views/admin/users/edit.html.erb
<% content_for :title, "Admin: Edit User: #{@user.name}" %>
<% breadcrumb :edit_user, @user %>

<main class="clearfix">
  <section class="workspace cf">
    <%= form_for(@user, url: admin_user_path(@user), html: { method: :put, class: 'profile-form edit-form split cf'}) do |f| %>
      <%= render partial: "admin/users/form", locals: {f: f} %>

      <div class="buttons cf">
        <%= f.submit "Save Changes", class: 'button save' %>
      </div>          
    <% end %>

    <section id="user-statistics" class="cf">
      <table id="statistics" class="stats">
        <thead>
          <tr>
            <th colspan="2">Statistics</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Documents</td>
            <td><%= @user.documents.length %></td>
          </tr>
          
          <tr>
            <td>Images</td>
            <td><%= @user.images.count %></td>
          </tr>
        </tbody>
      </table>

      <table id="documents-created" class="stats">
        <thead>
          <tr>
            <th colspan="2">Documents Created</th>
          </tr>
        </thead>

        <tbody>
          <% @templates.each do |template| %>
            <tr>
              <td><%= template.title %></td>
              <td><%= @template_ids.select{|tid| tid == template.id}.length %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>

    <div class="buttons cf">
      <%= link_to "See Users' Documents", workspace_admin_user_path(@user), class: "button save" %> 
    </div>
  </section><!--workspace-->    
</main>

app/views/admin/users/index.html.erb
<% content_for :title, "Admin: Manage Users" %>
<% breadcrumb :admin_users %>

<% content_for :breadcrumb_extras do %>
  <ol class="options cf">
    <%= link_to "<span class='icons'>C</span> Download".html_safe, export_admin_users_path(format: :csv) %>
  </ol>
<% end %>

<main class="clearfix">
  <section class="workspace cf">
    <p style="text-align:left;">You can manage users on this screen, or you can <%= link_to "create a new user", new_admin_user_path %>.</p>

    <% if @unapproved.count > 0 %>

    <h2>Unapproved Users</h2>
    <p>Click a user name to either approve or reject their Toolkit access.</p>

    <div class="table">
       <div class="rows">
           <%= render partial: "admin/users/header_row" %> 
          <% @unapproved.each do |user| %>
            <%= render partial: "admin/users/user_row", locals: {user: user} %>
          <% end %>
     </div><!--rows-->            
    </div><!--table-->     

    <% end %>

    <h2>Active Users</h2>
    <p>Click a user name to update their account information.</p>

    <div class="table">
       <div class="rows">
           <%= render partial: "admin/users/header_row" %> 
          <% @approved.each do |user| %>
            <%= render partial: "admin/users/user_row", locals: {user: user} %>
          <% end %>
     </div><!--rows-->            
    </div><!--table-->     

    <% if @rejected.count > 0 %>

    <h2>Rejected Users</h2>
    <p>Click a user name to modify their Toolkit access.</p>

    <div class="table">
       <div class="rows">
           <%= render partial: "admin/users/header_row" %> 
          <% @rejected.each do |user| %>
            <%= render partial: "admin/users/user_row", locals: {user: user} %>
          <% end %>
     </div><!--rows-->            
    </div><!--table-->     

    <% end %>


  </section><!--workspace--> 
</main>

app/views/admin/users/new.html.erb
<% breadcrumb :admin_users %>

<main class="clearfix">
  <section class="workspace cf">
   <%= form_for(@user, url: admin_users_path, html: { method: :post, class: 'profile-form edit-form split cf'}) do |f| %>

		<%= render partial: "admin/users/form", locals: { f: f } %>
    
    <div class="buttons cf">
      <%= f.submit "Create User", class: 'button save' %>
    </div>

          
   <% end %>

  </section><!--workspace-->
      
</main>

app/views/admin/users/workspace.html.erb
<section class="workspace cf">
  <%= render   @documents %>
  <%= paginate @documents %>
</section>